version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 
      python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      -  env_settings.env
    volumes:
      - ./db.sqlite3:/db.sqlite3